name: Publish to pub.dev

on:
  push:
    tags:
      - 'dart_helper_utils-v*'

jobs:
  publish:
    permissions:
      contents: read
      id-token: write
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
